baseURL: "http://example.org/"
languageCode: "en-us"
title: "Recipe Book"
theme: "simple-recipe"

params:
  help: true
  defaultRecipeImage: "/images/xkcd720.png"
  email: "recipes@example.com"

menu:
  main:
    - name: Category
      weight: 2
      url: /category/
    - name: Cuisine
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags
